<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>CW.ico</ApplicationIcon>
    <Copyright>dexyfex</Copyright>
    <Company>dexyfex software</Company>
    <Authors>dexyfex</Authors>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
    <PackageReference Include="FCTB" Version="2.16.24" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="SharpDX.XAudio2" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeWalker.Core\CodeWalker.Core.csproj" />
    <ProjectReference Include="..\CodeWalker.WinForms\CodeWalker.WinForms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <BuildOutputFiles Include="$(OutDir)**\*.*" Exclude="$(OutDir)Settings.xml" />
      <IconFiles Include="$(ProjectDir)..\icons\**\*.*" />
      <ShaderFiles Include="$(ProjectDir)..\Shaders\**\*.*" />
      <NvttFiles Include="$(ProjectDir)..\CodeWalker.NVTT\bin\Release\*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(BuildOutputFiles)" DestinationFolder="$(ProjectDir)..\x64\$(Configuration)\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(IconFiles)" DestinationFolder="$(ProjectDir)..\x64\$(Configuration)\icons\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ShaderFiles)" DestinationFolder="$(ProjectDir)..\x64\$(Configuration)\Shaders\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(NvttFiles)" DestinationFolder="$(ProjectDir)..\x64\$(Configuration)\" SkipUnchangedFiles="true" Condition="Exists('$(ProjectDir)..\CodeWalker.NVTT\bin\Release\CodeWalker.NVTT.dll')" />
    <Message Text="Copied build output, icons, shaders, to x64\$(Configuration)" Importance="high" />
  </Target>

</Project>